#!/bin/sh

function usage {
    cat <<EOF
$(basename ${0}) is a tool for ...

Usage:
    $(basename ${0}) [command] [<options>]

Options:
    --version, -v     print $(basename ${0}) version
    --help, -h        print this
EOF
}

function lack_of_necessary_param() {
  echo "-cオプションでのコンテスト指定は必須です。"
  exit 1
}

baseurl="https://atcoder.jp/contests/"
endpoint="/submissions?"

while getopts c:t:l:s:u:h OPT; do
    case $OPT in
        c ) FLG_C="TRUE" ; VALUE_C="$OPTARG" ;;
        t ) FLG_T="TRUE" ; VALUE_T="$OPTARG" ;;
        l ) FLG_L="TRUE" ; VALUE_L="$OPTARG" ;;
        s ) FLG_S="TRUE" ; VALUE_S="$OPTARG" ;;
        u ) FLG_U="TRUE" ; VALUE_U="$OPTARG" ;;
    esac
done

if [ "$FLG_C" != "TRUE" ]; then
    lack_of_necessary_param
else
    echo "${baseurl}${VALUE_C}${endpoint}"
fi;